# Generated by Django 5.1.4 on 2025-01-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
    ]
